Resources:
  GetVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: consultavideosfunction/
      Runtime: java17
      Handler: br.com.fiap.consultavideos.App::handleRequest

      Environment:
        Variables:
          VIDEOS_TABLE_NAME: fiapeatsdb
          AWS_REGION: us-east-1

      Policies:
        - DynamoDBReadPolicy:
            TableName: fiapeatsdb

      Events:
        GetVideosApi:
          Type: Api
          Properties:
            Path: /videos
            Method: get
